project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!posts/2021-07-28-spanish-flu-mortality/*.Rmd"

website:
  favicon: assets/favicon.ico
  title: "Interlude One"
  site-url: https://interludeone.com/
  navbar:
    background: "#FCFCFC"
    logo: assets/favicon_logo.ico
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: cv.qmd
        text: CV
      # - href: content/phd-planning.qmd
      - href: content/teaching.qmd
      - href: content/research.qmd
        text: Research
      - href: content/publications.qmd
      - href: content/data.qmd
        text: Data
    right: 
      - text: "Web Apps"
        menu:
        - text: "Second Hand Car Price Comparison Tool"
          href: http://jonathan-jayes.shinyapps.io/gumtree-price-explorer
        - text: "Production Functions Shiny App"
          href: https://github.com/j-jayes/production-functions
        - text: "Economics literature explorer"
          href: https://github.com/j-jayes/NBER-methods
        - text: "Europe's Regional Development Explorer"
          href: https://github.com/j-jayes/Roses-Wolf-database-on-regional-GDP
      - text: "Fun stuff"
        menu:
        - text: "My personal cookbook"
          href: "https://j-jayes.github.io/recipes/"
        - text: "Generative AI reports"
          href: "content/generative-ai-articles-listing.qmd"
      - text: "{{< fa brands github >}}"
        href: https://github.com/j-jayes/interlude-one
      - icon: rss
        href: index.xml


format:
  html:
    theme: assets/custom.scss
    toc: true
    include-in-header:
      - text: |
          <script data-goatcounter="https://j0nathan.goatcounter.com/count"
          async src="//gc.zgo.at/count.js"></script>

execute:
  echo: false
  warning: false
  message: false
  freeze: true

# react:
#   resources: "posts/2025-02-27-react-production-functions/_resources"
#   components: "posts/2025-02-27-react-production-functions/_components"

react:
  resources: "_components"
  components: "_components"
