project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!posts/2021-07-28-spanish-flu-mortality/*.Rmd"

website:
  favicon: assets/favicon.ico
  title: "Interlude One"
  navbar:
    logo: assets/favicon_logo.ico
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: assets/custom.scss
    toc: true

execute:
  echo: false
  warning: false
  message: false
  freeze: true
