project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "!posts/2021-07-28-spanish-flu-mortality/*.Rmd"

website:
  favicon: assets/favicon.ico
  title: "Interlude One"
  navbar:
    logo: assets/favicon_logo.ico
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: content/consulting.qmd
      - href: content/teaching.qmd
      - href: content/publications.qmd
      - href: content/data.qmd
        text: Data
    right: 
      - text: "Web Apps"
        menu:
        - text: "Second Hand Car Price Comparison Tool"
          href: http://jonathan-jayes.shinyapps.io/gumtree-price-explorer
        - text: "Production Functions Shiny App"
          href: https://github.com/j-jayes/production-functions
        - text: "Economics literature explorer"
          href: https://github.com/j-jayes/NBER-methods
        - text: "Europe's Regional Development Explorer"
          href: https://github.com/j-jayes/Roses-Wolf-database-on-regional-GDP
      - text: "{{< fa brands github >}}"
        href: https://github.com/j-jayes/interlude-one


format:
  html:
    theme: assets/custom.scss
    toc: true

execute:
  echo: false
  warning: false
  message: false
  freeze: true
